---
title: JAVA 예외(Exception) 정복하기
date: 2023-11-19 13:33:00 +0900
categories: [Java]
tags: [Java,Exception,예외]
toc: true
toc_sticky: true
toc_label: 목차
math: true
mermaid: true
---

자바에서 예외(Exception)는 프로그램의 실행 도중에 발생할 수 있는 비정상적인 상황을 말한다.

예외는 일반적으로 프로그램이 실행 중에 예상치 못한 오류 상황이나 예외적인 조건에 직면했을때 발생한다.

예외가 발생하면 프로그램이 종료될 수 있지만, 예외 처리를 통해 실행 상태를 유지하고 적절한 조치를 취할 수 있다.

## 💡 예외의 종류
1. 일반 예외 (Exception)   
   컴파일러가 예외 처리 코드 여부를 검사하는 예외를 말한다.   
   `IOException` 와 같은 파일 조작시 발생하는 예외가 여기에 속한다.


2. 실행 예외 (RuntimeException)   
   컴파일러가 예외 처리 코드 여부를 검사하지 않은 예외를 말한다.   
   `NullPointException` 과 같은 런타임시 발생하는 예외가 여기에 속한다.

## 💡 예외처리 코드
예외처리 코드란 예외가 발생했을 떄 프로그램의 갑작스러운 종료를 막고 실행을 유지할 수 있는 코드를 말한다.

예외 처리 코드는 `try-catch-finally` 블록으로 구성된다.

```java
try {
    //예외가 발생할 수 있는 코드
} catch (예외 클래스 e) {
    //예외처리
} finally {
    //항상실행
}
```
`catch` 블록이 여러개일지라도 `catch` 블록은 단 하나만 실행된다.

`try` 블록에서 동시 다발적으로 예외가 발생하지 않으며, 하나의 예외가 발생하면 즉시 멈추고 `catch` 블록 으로 이동하기 때문이다.

## 💡 예외 떠넘기기
메소드 내부에서 예외가 발생할 때 `try-catch` 블록으로 예외를 처리하는 것이 일반적이지만,

메소드를 호출한 곳으로 예외를 떠넘길 수 있다. 이떄 사용하는 키워드는 `throws` 이다.

```java
public void method1() {
	try{
		method2(); //메소드2호출 
	} catch(ClassNotFountException e) {
		System.out.println("예외처리 : " + e.getMessage());
	}
}

public void method2() throws ClassNotFundException {
	Class.forName("...")
}
```
`thorws` 키워드가 붙어있는 메소드에서 해당 예외를 처리하지 않고 예외를 메소드 호출한 곳으로 떠넘겼다.

이 메소드를 호출한 `method1()` 에서 예외를 받아서 처리해야 한다.

떠넘길 예외가 많을 경우 `throws Exception` 또는 `throws Throwable` 만으로 모든 예외를 떠넘길 수 있다.

main 메서드에서도 예외를 떠넘길 수 있는데 결국 JVM이 최종적으로 예외를 처리하게 된다.

JVM은 예외의 내용을 콘솔에 출력하는 것으로 예외를 처리한다.


## 💡 예외의 흐름
예외가 발생하면 해당 예외 클래스의 객체가 생성되고 이 객체는 호출 스택을 따라 메서드들을 거슬러 올라가면서 예외를 처리할 수 있는 `try-catch` 블록을 찾는다. 만약 호출 스택 맨 위 `main()` 까지 예외를 처리 할 수 없는 블록이 없다면 프로그램은 비정상 종료되고, 예외에 대한 정보가 출력된다.  

<hr>

1. 예외 발생  
   프로그램이 실행 중에 어떤 이유로 예외가 발생한다.  

2. 예외 객체 생성    
   예외가 발생하면 해당 예외 클래스의 객체가 생성된다.  

3. 호출 스택 검색  
   예외가 발생한 지점부터 호출 스택을 따라 올라가며 `try-catch` 블록을 찾는다.  

4. 처리 가능한 블록 발견  
   호출 스택을 따라 올라가면서 예외를 처리할 수 있는 `try-catch` 블록을 찾으면 해당 블록이 실행된다.  

5. 예외 처리  
   찾은 `catch`블록에서 예외를 처리한다.  

6. 처리 가능한 블록이 없을 경우  
   호출 스택의 맨 위까지 예외를 처리할 수 있는 블록이 없다면 프로그램은 비정상 종료된다.  

<hr>

```java
public class ExceptionExample {

    public static void main(String[] args) {
        try {
            methodA();
        } catch (CustomException e) {
            System.out.println("Caught CustomException: " + e.getMessage());
        }
    }

    public static void methodA() {
        try {
            methodB();
        } catch (NullPointerException e) {
            System.out.println("Caught NullPointerException: " + e.getMessage());
        }
    }

    public static void methodB() {
        throw new CustomException("Custom Exception in methodB");
    }
}

class CustomException extends Exception {
    public CustomException(String message) {
        super(message);
    }
}
```
1. `methodB` 에서 `CustomException` 예외를 발생 시켰다.   
2. 호출 스택을 따라 올라가며 `try-catch` 블록을 찾는다.
3. `methodB` 에서 발생한 예외를 처리할 수 있는 `try-catch`블록은 `methodA` 블록에있다.
4. `methodA`의 `catch`블록의 의해 예외가 처리된다.

### 📌 만약 `methodA`에 try-catch 블록이 없다면?
<hr>

만약 `methodA` 에 `try-catch` 블록이 없다면, 예외는 `main`메서드로 전파된다. 

이 경우 `main` 메서드에서도 `try-catch` 블록이 없다면 예외는 최종적으로 스레드의 실행을 중단하고

예외 정보를 출력한 후 프로그램이 종료된다.

```java
public class ExceptionExample {

    public static void main(String[] args) {
        try {
            methodA();
        } catch (CustomException e) {
            System.out.println("Caught CustomException in main: " + e.getMessage());
        }
    }

    public static void methodA() {
        methodB();
    }

    public static void methodB() {
        throw new CustomException("Custom Exception in methodB");
    }
}

class CustomException extends Exception {
    public CustomException(String message) {
        super(message);
    }
}
```

<p align="center">
  <img src="../../../../assets/img/2023-11-19-14-06-16.png">
</p>

### 📌 그럼 왜 `throws` 키워드를 사용하는 것일까?

<hr>

예외의 흐름에서 자동으로 호출 스택을 따라 올라가며 `try-catch`문을 찾는다고 하였다.

그러면 예외를 떠넘기는 `thorws` 키워드를 붙일 이유가 없지않을까?


1. 예외 전파 (Exception Propagetion)   
   메서드는 예외가 발생하면 그 예외는 자동으로 해당 메서드를 호출한 상위 메서드로 전파된다.  
   이는 `throws` 키워드를 사용하지 않아도 발생하는 것으로 자바에서는 모든 예외가 `Throwable` 클래스를 상속받고 있기 때문에 가능하다.  

2. 예외 떠넘기기   
   `throws` 키워드는 메서드 선언부에서 사용되며 해당 메서드에서 발생할 수 있는 예외를 명시적으로 나열한다.  
   이는 컴파일러에게 이 메서드를 호출하는 코드에서 이 예외를 처리하도록 강제하는 역할을 한다.

**`throws` 키워드를 사용하는 이유**  
1. 명시적인 예외 처리 요구가 가능하다.  
   호출하는 코드에 명시적으로 예외 처리를 요구함으로써 개발자에게 어떤 예외가 발생했는지 알려줌.  
2. 강제성
   `throws` 키워드를 사용함으로써 컴파일러가 해당 예외처리를 강제하기 때문에  
   개발자가 예외 처리를 잊었을 시 런타임 오류를 방지할 수 있다.

## 💡 자바 예외클래스의 상속도

<p align="center">
  <img src="../../../../assets/img/2023-11-19-14-29-34.png">
</p>